version: "2"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    image: webapp-frontend
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ".:/usr/src/app"
      - "/usr/src/app/node_modules"
    environment:
      - NODE_ENV=development
    networks:
      - webappnetwork
  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    image: webapp-web
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - .:/myapp
      - /myapp/node_modules
    networks:
      - webappnetwork

networks:
  webappnetwork:
    driver: bridge      